vim.o.termguicolors = true
vim.wo.number = true -- Make line numbers default
vim.o.relativenumber = true
vim.o.mouse = 'a' -- Enable mouse mode
vim.o.clipboard = 'unnamedplus' -- Sync clipboard between OS and Neovim.
vim.o.breakindent = true -- Enable break indent
vim.o.numberwidth = 2 -- set number column width to 2 {default 4}
vim.o.shiftwidth = 2 -- the number of spaces inserted for each indentation
vim.o.tabstop = 2 -- insert n spaces for a tab
vim.o.softtabstop = 2 -- Number of spaces that a tab counts for while performing editing operations
vim.o.expandtab = true -- convert tabs to spaces
vim.o.autoindent = true -- copy indent from current line when starting new one
vim.o.splitbelow = true -- force all horizontal splits to go below current window
vim.o.splitright = true -- force all vertical splits to go to the right of current window
vim.o.laststatus = 0 -- hide status bar
vim.o.showmode = false -- hide mode cause already have lualine
vim.o.undofile = true -- save undo history
vim.o.hlsearch = true -- highlight search result
vim.o.termguicolors = true -- enable 24-bit RGB colors
vim.o.swapfile = false -- don't use swapfile
vim.o.fileencoding = 'utf-8' -- the encoding written to file
vim.o.scrolloff = 8
